repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/

      - id: ruff-format
        files: ^backend/

  - repo: local
    hooks:
      - id: mypy
        name: Mypy
        entry: bash -c "cd backend && python3 -m mypy ."
        language: system
        types: [python]
        files: ^backend/

  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: bash -c 'cd frontend && npx prettier --write . > /dev/null'
        language: system
        files: ^frontend/
        types_or: [javascript, jsx, css, json, html]
