version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    networks:
      - back-network
    volumes:
      - ./backend:/app # @TODO: is it necessary?
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    secrets:
      - db_user_password
      - db_user_login
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    volumes:
      - ./frontend:/app # @TODO: is it necessary?
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

  database:
    build: ./database
    hostname: database
    networks:
      back-network:
        aliases:
          - database
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user_login
      POSTGRES_PASSWORD_FILE: /run/secrets/db_user_password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db_user_password
      - db_user_login
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/db_user_login)"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  back-network:
    driver: bridge

secrets:
  db_user_password:
    file: ./.secrets/db_user_password.txt
  db_user_login:
    file: ./.secrets/db_user_login.txt
  jwt_secret:
    file: ./.secrets/jwt_secret.txt
